"""empty message

Revision ID: 2df0ff2bf485
Revises: 1a458f9d2902
Create Date: 2023-04-16 14:40:14.912086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df0ff2bf485'
down_revision = '1a458f9d2902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
